services:
  streamlit:
    image: ${DC_IMAGE_NAME}:${DC_IMAGE_TAG}
    ports:
      - ${DC_APP_PORT}:${DC_APP_PORT}
    command: python3 -m streamlit run Streamlit_app.py
    networks:
      - my_network_from_compose

networks:
  my_network_from_compose:
